# Generated by Django 4.1.7 on 2023-03-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=50)),
                ('buy', models.IntegerField()),
                ('sell', models.IntegerField()),
                ('season', models.CharField(choices=[], max_length=30)),
            ],
        ),
    ]
