# Generated by Django 4.1.7 on 2023-03-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_remove_crop_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biome_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='crop',
            new_name='crop_name',
        ),
        migrations.AddField(
            model_name='crop',
            name='image_name',
            field=models.CharField(default='static/crops/images/space.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='crop',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='biome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cropss', to='crops.biome'),
        ),
        migrations.AddField(
            model_name='crop',
            name='grow_season',
            field=models.ManyToManyField(to='crops.seasons'),
        ),
    ]
