# Generated by Django 4.1.7 on 2023-03-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_biome_seasons_rename_crop_crop_crop_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasons',
            options={'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterField(
            model_name='crop',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
