# Generated by Django 4.1.7 on 2023-03-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_alter_seasons_options_alter_crop_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='slug',
        ),
    ]
