# Generated by Django 4.1.7 on 2023-03-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_remove_crop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
